services:
  - type: web
    name: battleship-api
    env: node
    plan: free
    region: frankfurt
    buildCommand: cd api && npm install
    startCommand: cd api && node index.js
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: MONGODB_URL
        sync: false
      - key: PORT
        value: 3000